# This is experimental and not Production Grade

# this is build stage
FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /core-banking-system

COPY . .

RUN mvn clean package

# this is run stage
FROM eclipse-temurin:21-jre
WORKDIR /core-banking-system
COPY --from=build /core-banking-system/api/target/*.jar api.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "api.jar"]