INSERT INTO core.CUSTOMER (FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, CITY, STATE, PIN_CODE, COUNTRY) VALUES ('JOHN', 'A.', 'DOE', 'JOHN.DOE@EXAMPLE.COM', '+1-555-1234567', '123 MAIN STREET', 'NEW YORK', 'NEW YORK', '10001', 'USA');

INSERT INTO core.BANK_PRODUCT (NAME, DESCRIPTION) VALUES ('Savings Account', 'A standard savings account with competitive interest rate.');
