package io.github.cbs.service.mapper;

import io.github.cbs.domain.entity.Customer;
import io.github.cbs.dto.req.CustomerReq;
import io.github.cbs.dto.res.CustomerRes;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface CustomerMapper {

    @Mapping(target = "id", ignore = true)
    Customer toEntity(CustomerReq request); // ID is generated by DB

    CustomerRes toResponse(Customer entity);
}